spring.application.name=MinhTuyetFood

spring.datasource.url=jdbc:h2:mem:hintran
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=hintran
spring.datasource.password=hintran

spring.jpa.show-sql=true